<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>promise的实现--taotao</title>
</head>
<body>
	<script src="_Promise.js"></script>
	<script>
	// 切换原生的promise
	 // const _Promise = Promise

	function start() {
	  return new _Promise((resolve, reject) => {
	    resolve('start');
	  });
	}

	start()
	.then(data => {
		// promise start
		console.log('result of start: ', data);
		return _Promise.resolve(1); // p1
	})
	.then(data => {
		// promise p1
		console.log('result of p1: ', data);
		return _Promise.reject({
			notReal_PromiseException: true,
		}); // p2
	})
	.then(data => {
		// promise p2
		console.log('result of p2: ', data);
		return _Promise.resolve(3); // p3
	})
	.catch(ex => {
		console.log('ex: ', ex);
		if (ex.notReal_PromiseException) {
			// 一切正常，只是通过 catch 方法来中止 promise chain
			// 也就是中止 promise p2 的执行
			return true;
		}
		// 真正发生异常
		return false;
	});

	var p = new _Promise((re, rj) => {
		for (let i = 0; i < 10; i++) {
			setTimeout(_ => re(i * 10, 'taotao' +i), 1000)
		}
	})
	setTimeout(_ => {
		p.then((res, name) => console.log(res, name, '21'))
	}, 1200)
	p.then((res,name) => {
	    console.log(res, name)
		return 'dd'
	})
	.then(_ => {
		console.log(_)
		return 'aa'
	}).catch(e => {
		console.warn(e)
	})


	const test = _ => {
	    var s = 'this is function'
		if (s.includes(this)) {
	        return 'taotao'
		}
	}
//
	function getFn (fn) {
	    return new _Promise((re, rj) => {
			const str = getFnBody(fn)
			setTimeout(_ => {
			    str ? re(str) : rj('no function str')
			}, 1000)
		})
	}

	var p = getFn(test)
	p.then(str => {
		console.log(str)
		return _Promise.reject('err')
	}).catch(err => {
	    console.warn(err)
	}).then(str => {
	    console.log(str)
	})
	</script>
</body>
</html>